// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        v3.20.1
// source: landlord.proto

package protos

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// JoinRequest 加入匹配队列请求
type JoinRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	PlayerName string `protobuf:"bytes,1,opt,name=player_name,json=playerName,proto3" json:"player_name,omitempty"`
}

func (x *JoinRequest) Reset() {
	*x = JoinRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_landlord_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *JoinRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JoinRequest) ProtoMessage() {}

func (x *JoinRequest) ProtoReflect() protoreflect.Message {
	mi := &file_landlord_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JoinRequest.ProtoReflect.Descriptor instead.
func (*JoinRequest) Descriptor() ([]byte, []int) {
	return file_landlord_proto_rawDescGZIP(), []int{0}
}

func (x *JoinRequest) GetPlayerName() string {
	if x != nil {
		return x.PlayerName
	}
	return ""
}

// BidRequest 叫分请求
type BidRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Score int32 `protobuf:"varint,1,opt,name=score,proto3" json:"score,omitempty"` // 0=不叫, 1/2/3=叫分
}

func (x *BidRequest) Reset() {
	*x = BidRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_landlord_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BidRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BidRequest) ProtoMessage() {}

func (x *BidRequest) ProtoReflect() protoreflect.Message {
	mi := &file_landlord_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BidRequest.ProtoReflect.Descriptor instead.
func (*BidRequest) Descriptor() ([]byte, []int) {
	return file_landlord_proto_rawDescGZIP(), []int{1}
}

func (x *BidRequest) GetScore() int32 {
	if x != nil {
		return x.Score
	}
	return 0
}

// PlayRequest 出牌请求
type PlayRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	CardIds []int32 `protobuf:"varint,1,rep,packed,name=card_ids,json=cardIds,proto3" json:"card_ids,omitempty"` // 要出的牌ID列表
}

func (x *PlayRequest) Reset() {
	*x = PlayRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_landlord_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PlayRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlayRequest) ProtoMessage() {}

func (x *PlayRequest) ProtoReflect() protoreflect.Message {
	mi := &file_landlord_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlayRequest.ProtoReflect.Descriptor instead.
func (*PlayRequest) Descriptor() ([]byte, []int) {
	return file_landlord_proto_rawDescGZIP(), []int{2}
}

func (x *PlayRequest) GetCardIds() []int32 {
	if x != nil {
		return x.CardIds
	}
	return nil
}

// PassRequest 不出请求
type PassRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *PassRequest) Reset() {
	*x = PassRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_landlord_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PassRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PassRequest) ProtoMessage() {}

func (x *PassRequest) ProtoReflect() protoreflect.Message {
	mi := &file_landlord_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PassRequest.ProtoReflect.Descriptor instead.
func (*PassRequest) Descriptor() ([]byte, []int) {
	return file_landlord_proto_rawDescGZIP(), []int{3}
}

// JoinResponse 加入匹配队列响应
type JoinResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Code    int32  `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`                  // 0=成功
	Message string `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`             // 提示消息
	RoomId  string `protobuf:"bytes,3,opt,name=room_id,json=roomId,proto3" json:"room_id,omitempty"` // 房间ID
	Seat    int32  `protobuf:"varint,4,opt,name=seat,proto3" json:"seat,omitempty"`                  // 座位号 (0, 1, 2)
}

func (x *JoinResponse) Reset() {
	*x = JoinResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_landlord_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *JoinResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JoinResponse) ProtoMessage() {}

func (x *JoinResponse) ProtoReflect() protoreflect.Message {
	mi := &file_landlord_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JoinResponse.ProtoReflect.Descriptor instead.
func (*JoinResponse) Descriptor() ([]byte, []int) {
	return file_landlord_proto_rawDescGZIP(), []int{4}
}

func (x *JoinResponse) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *JoinResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *JoinResponse) GetRoomId() string {
	if x != nil {
		return x.RoomId
	}
	return ""
}

func (x *JoinResponse) GetSeat() int32 {
	if x != nil {
		return x.Seat
	}
	return 0
}

// BidResponse 叫分响应
type BidResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Code    int32  `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Message string `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
}

func (x *BidResponse) Reset() {
	*x = BidResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_landlord_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BidResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BidResponse) ProtoMessage() {}

func (x *BidResponse) ProtoReflect() protoreflect.Message {
	mi := &file_landlord_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BidResponse.ProtoReflect.Descriptor instead.
func (*BidResponse) Descriptor() ([]byte, []int) {
	return file_landlord_proto_rawDescGZIP(), []int{5}
}

func (x *BidResponse) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *BidResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

// PlayResponse 出牌响应
type PlayResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Code    int32  `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Message string `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
}

func (x *PlayResponse) Reset() {
	*x = PlayResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_landlord_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PlayResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlayResponse) ProtoMessage() {}

func (x *PlayResponse) ProtoReflect() protoreflect.Message {
	mi := &file_landlord_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlayResponse.ProtoReflect.Descriptor instead.
func (*PlayResponse) Descriptor() ([]byte, []int) {
	return file_landlord_proto_rawDescGZIP(), []int{6}
}

func (x *PlayResponse) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *PlayResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

// PassResponse 不出响应
type PassResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Code    int32  `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Message string `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
}

func (x *PassResponse) Reset() {
	*x = PassResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_landlord_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PassResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PassResponse) ProtoMessage() {}

func (x *PassResponse) ProtoReflect() protoreflect.Message {
	mi := &file_landlord_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PassResponse.ProtoReflect.Descriptor instead.
func (*PassResponse) Descriptor() ([]byte, []int) {
	return file_landlord_proto_rawDescGZIP(), []int{7}
}

func (x *PassResponse) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *PassResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

// PlayerInfo 玩家基础信息
type PlayerInfo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Uid       string `protobuf:"bytes,1,opt,name=uid,proto3" json:"uid,omitempty"`
	Name      string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Seat      int32  `protobuf:"varint,3,opt,name=seat,proto3" json:"seat,omitempty"`
	IsAi      bool   `protobuf:"varint,4,opt,name=is_ai,json=isAi,proto3" json:"is_ai,omitempty"`
	CardCount int32  `protobuf:"varint,5,opt,name=card_count,json=cardCount,proto3" json:"card_count,omitempty"` // 剩余手牌数
}

func (x *PlayerInfo) Reset() {
	*x = PlayerInfo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_landlord_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PlayerInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlayerInfo) ProtoMessage() {}

func (x *PlayerInfo) ProtoReflect() protoreflect.Message {
	mi := &file_landlord_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlayerInfo.ProtoReflect.Descriptor instead.
func (*PlayerInfo) Descriptor() ([]byte, []int) {
	return file_landlord_proto_rawDescGZIP(), []int{8}
}

func (x *PlayerInfo) GetUid() string {
	if x != nil {
		return x.Uid
	}
	return ""
}

func (x *PlayerInfo) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *PlayerInfo) GetSeat() int32 {
	if x != nil {
		return x.Seat
	}
	return 0
}

func (x *PlayerInfo) GetIsAi() bool {
	if x != nil {
		return x.IsAi
	}
	return false
}

func (x *PlayerInfo) GetCardCount() int32 {
	if x != nil {
		return x.CardCount
	}
	return 0
}

// GameStartPush 游戏开始推送
type GameStartPush struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	RoomId      string        `protobuf:"bytes,1,opt,name=room_id,json=roomId,proto3" json:"room_id,omitempty"`
	Players     []*PlayerInfo `protobuf:"bytes,2,rep,name=players,proto3" json:"players,omitempty"`
	YourCards   []int32       `protobuf:"varint,3,rep,packed,name=your_cards,json=yourCards,proto3" json:"your_cards,omitempty"` // 你的手牌ID列表
	FirstBidder int32         `protobuf:"varint,4,opt,name=first_bidder,json=firstBidder,proto3" json:"first_bidder,omitempty"`  // 首先叫分的座位
}

func (x *GameStartPush) Reset() {
	*x = GameStartPush{}
	if protoimpl.UnsafeEnabled {
		mi := &file_landlord_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GameStartPush) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GameStartPush) ProtoMessage() {}

func (x *GameStartPush) ProtoReflect() protoreflect.Message {
	mi := &file_landlord_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GameStartPush.ProtoReflect.Descriptor instead.
func (*GameStartPush) Descriptor() ([]byte, []int) {
	return file_landlord_proto_rawDescGZIP(), []int{9}
}

func (x *GameStartPush) GetRoomId() string {
	if x != nil {
		return x.RoomId
	}
	return ""
}

func (x *GameStartPush) GetPlayers() []*PlayerInfo {
	if x != nil {
		return x.Players
	}
	return nil
}

func (x *GameStartPush) GetYourCards() []int32 {
	if x != nil {
		return x.YourCards
	}
	return nil
}

func (x *GameStartPush) GetFirstBidder() int32 {
	if x != nil {
		return x.FirstBidder
	}
	return 0
}

// BidTurnPush 轮到某人叫分
type BidTurnPush struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Seat   int32 `protobuf:"varint,1,opt,name=seat,proto3" json:"seat,omitempty"`                   // 当前叫分的座位号
	MaxBid int32 `protobuf:"varint,2,opt,name=max_bid,json=maxBid,proto3" json:"max_bid,omitempty"` // 当前最高叫分
}

func (x *BidTurnPush) Reset() {
	*x = BidTurnPush{}
	if protoimpl.UnsafeEnabled {
		mi := &file_landlord_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BidTurnPush) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BidTurnPush) ProtoMessage() {}

func (x *BidTurnPush) ProtoReflect() protoreflect.Message {
	mi := &file_landlord_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BidTurnPush.ProtoReflect.Descriptor instead.
func (*BidTurnPush) Descriptor() ([]byte, []int) {
	return file_landlord_proto_rawDescGZIP(), []int{10}
}

func (x *BidTurnPush) GetSeat() int32 {
	if x != nil {
		return x.Seat
	}
	return 0
}

func (x *BidTurnPush) GetMaxBid() int32 {
	if x != nil {
		return x.MaxBid
	}
	return 0
}

// BidResultPush 叫分结果
type BidResultPush struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Seat  int32  `protobuf:"varint,1,opt,name=seat,proto3" json:"seat,omitempty"`   // 叫分玩家的座位
	Score int32  `protobuf:"varint,2,opt,name=score,proto3" json:"score,omitempty"` // 叫的分数 (0=不叫)
	Name  string `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`    // 玩家名字
}

func (x *BidResultPush) Reset() {
	*x = BidResultPush{}
	if protoimpl.UnsafeEnabled {
		mi := &file_landlord_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BidResultPush) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BidResultPush) ProtoMessage() {}

func (x *BidResultPush) ProtoReflect() protoreflect.Message {
	mi := &file_landlord_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BidResultPush.ProtoReflect.Descriptor instead.
func (*BidResultPush) Descriptor() ([]byte, []int) {
	return file_landlord_proto_rawDescGZIP(), []int{11}
}

func (x *BidResultPush) GetSeat() int32 {
	if x != nil {
		return x.Seat
	}
	return 0
}

func (x *BidResultPush) GetScore() int32 {
	if x != nil {
		return x.Score
	}
	return 0
}

func (x *BidResultPush) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

// LandlordDecidedPush 地主确定推送
type LandlordDecidedPush struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	LandlordSeat int32   `protobuf:"varint,1,opt,name=landlord_seat,json=landlordSeat,proto3" json:"landlord_seat,omitempty"`     // 地主座位号
	LandlordName string  `protobuf:"bytes,2,opt,name=landlord_name,json=landlordName,proto3" json:"landlord_name,omitempty"`      // 地主名字
	BottomCards  []int32 `protobuf:"varint,3,rep,packed,name=bottom_cards,json=bottomCards,proto3" json:"bottom_cards,omitempty"` // 底牌（所有人可见）
	YourCards    []int32 `protobuf:"varint,4,rep,packed,name=your_cards,json=yourCards,proto3" json:"your_cards,omitempty"`       // 更新后的你的手牌
	BidScore     int32   `protobuf:"varint,5,opt,name=bid_score,json=bidScore,proto3" json:"bid_score,omitempty"`                 // 最终叫分
}

func (x *LandlordDecidedPush) Reset() {
	*x = LandlordDecidedPush{}
	if protoimpl.UnsafeEnabled {
		mi := &file_landlord_proto_msgTypes[12]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *LandlordDecidedPush) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LandlordDecidedPush) ProtoMessage() {}

func (x *LandlordDecidedPush) ProtoReflect() protoreflect.Message {
	mi := &file_landlord_proto_msgTypes[12]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LandlordDecidedPush.ProtoReflect.Descriptor instead.
func (*LandlordDecidedPush) Descriptor() ([]byte, []int) {
	return file_landlord_proto_rawDescGZIP(), []int{12}
}

func (x *LandlordDecidedPush) GetLandlordSeat() int32 {
	if x != nil {
		return x.LandlordSeat
	}
	return 0
}

func (x *LandlordDecidedPush) GetLandlordName() string {
	if x != nil {
		return x.LandlordName
	}
	return ""
}

func (x *LandlordDecidedPush) GetBottomCards() []int32 {
	if x != nil {
		return x.BottomCards
	}
	return nil
}

func (x *LandlordDecidedPush) GetYourCards() []int32 {
	if x != nil {
		return x.YourCards
	}
	return nil
}

func (x *LandlordDecidedPush) GetBidScore() int32 {
	if x != nil {
		return x.BidScore
	}
	return 0
}

// PlayTurnPush 轮到某人出牌
type PlayTurnPush struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Seat      int32   `protobuf:"varint,1,opt,name=seat,proto3" json:"seat,omitempty"`                                   // 当前出牌的座位号
	CanPass   bool    `protobuf:"varint,2,opt,name=can_pass,json=canPass,proto3" json:"can_pass,omitempty"`              // 是否可以不出
	LastCards []int32 `protobuf:"varint,3,rep,packed,name=last_cards,json=lastCards,proto3" json:"last_cards,omitempty"` // 上一手出的牌（空表示自由出牌）
	LastSeat  int32   `protobuf:"varint,4,opt,name=last_seat,json=lastSeat,proto3" json:"last_seat,omitempty"`           // 上一手出牌的座位（-1 表示无）
}

func (x *PlayTurnPush) Reset() {
	*x = PlayTurnPush{}
	if protoimpl.UnsafeEnabled {
		mi := &file_landlord_proto_msgTypes[13]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PlayTurnPush) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlayTurnPush) ProtoMessage() {}

func (x *PlayTurnPush) ProtoReflect() protoreflect.Message {
	mi := &file_landlord_proto_msgTypes[13]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlayTurnPush.ProtoReflect.Descriptor instead.
func (*PlayTurnPush) Descriptor() ([]byte, []int) {
	return file_landlord_proto_rawDescGZIP(), []int{13}
}

func (x *PlayTurnPush) GetSeat() int32 {
	if x != nil {
		return x.Seat
	}
	return 0
}

func (x *PlayTurnPush) GetCanPass() bool {
	if x != nil {
		return x.CanPass
	}
	return false
}

func (x *PlayTurnPush) GetLastCards() []int32 {
	if x != nil {
		return x.LastCards
	}
	return nil
}

func (x *PlayTurnPush) GetLastSeat() int32 {
	if x != nil {
		return x.LastSeat
	}
	return 0
}

// CardPlayedPush 某人出了牌
type CardPlayedPush struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Seat      int32   `protobuf:"varint,1,opt,name=seat,proto3" json:"seat,omitempty"`                            // 出牌玩家的座位
	Cards     []int32 `protobuf:"varint,2,rep,packed,name=cards,proto3" json:"cards,omitempty"`                   // 出的牌ID
	HandType  string  `protobuf:"bytes,3,opt,name=hand_type,json=handType,proto3" json:"hand_type,omitempty"`     // 牌型名称
	CardCount int32   `protobuf:"varint,4,opt,name=card_count,json=cardCount,proto3" json:"card_count,omitempty"` // 该玩家剩余手牌数
	Name      string  `protobuf:"bytes,5,opt,name=name,proto3" json:"name,omitempty"`                             // 玩家名字
}

func (x *CardPlayedPush) Reset() {
	*x = CardPlayedPush{}
	if protoimpl.UnsafeEnabled {
		mi := &file_landlord_proto_msgTypes[14]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CardPlayedPush) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CardPlayedPush) ProtoMessage() {}

func (x *CardPlayedPush) ProtoReflect() protoreflect.Message {
	mi := &file_landlord_proto_msgTypes[14]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CardPlayedPush.ProtoReflect.Descriptor instead.
func (*CardPlayedPush) Descriptor() ([]byte, []int) {
	return file_landlord_proto_rawDescGZIP(), []int{14}
}

func (x *CardPlayedPush) GetSeat() int32 {
	if x != nil {
		return x.Seat
	}
	return 0
}

func (x *CardPlayedPush) GetCards() []int32 {
	if x != nil {
		return x.Cards
	}
	return nil
}

func (x *CardPlayedPush) GetHandType() string {
	if x != nil {
		return x.HandType
	}
	return ""
}

func (x *CardPlayedPush) GetCardCount() int32 {
	if x != nil {
		return x.CardCount
	}
	return 0
}

func (x *CardPlayedPush) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

// PassPush 某人不出
type PassPush struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Seat int32  `protobuf:"varint,1,opt,name=seat,proto3" json:"seat,omitempty"` // 不出的座位
	Name string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`  // 玩家名字
}

func (x *PassPush) Reset() {
	*x = PassPush{}
	if protoimpl.UnsafeEnabled {
		mi := &file_landlord_proto_msgTypes[15]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PassPush) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PassPush) ProtoMessage() {}

func (x *PassPush) ProtoReflect() protoreflect.Message {
	mi := &file_landlord_proto_msgTypes[15]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PassPush.ProtoReflect.Descriptor instead.
func (*PassPush) Descriptor() ([]byte, []int) {
	return file_landlord_proto_rawDescGZIP(), []int{15}
}

func (x *PassPush) GetSeat() int32 {
	if x != nil {
		return x.Seat
	}
	return 0
}

func (x *PassPush) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

// GameEndPush 游戏结束
type GameEndPush struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	WinnerSeat  int32  `protobuf:"varint,1,opt,name=winner_seat,json=winnerSeat,proto3" json:"winner_seat,omitempty"`    // 赢家座位
	WinnerName  string `protobuf:"bytes,2,opt,name=winner_name,json=winnerName,proto3" json:"winner_name,omitempty"`     // 赢家名字
	IsLandlord  bool   `protobuf:"varint,3,opt,name=is_landlord,json=isLandlord,proto3" json:"is_landlord,omitempty"`    // 赢家是否是地主
	LandlordWin bool   `protobuf:"varint,4,opt,name=landlord_win,json=landlordWin,proto3" json:"landlord_win,omitempty"` // 地主是否获胜
	BidScore    int32  `protobuf:"varint,5,opt,name=bid_score,json=bidScore,proto3" json:"bid_score,omitempty"`          // 叫分倍数
	BombCount   int32  `protobuf:"varint,6,opt,name=bomb_count,json=bombCount,proto3" json:"bomb_count,omitempty"`       // 炸弹数量（翻倍用）
	Spring      bool   `protobuf:"varint,7,opt,name=spring,proto3" json:"spring,omitempty"`                              // 是否春天
}

func (x *GameEndPush) Reset() {
	*x = GameEndPush{}
	if protoimpl.UnsafeEnabled {
		mi := &file_landlord_proto_msgTypes[16]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GameEndPush) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GameEndPush) ProtoMessage() {}

func (x *GameEndPush) ProtoReflect() protoreflect.Message {
	mi := &file_landlord_proto_msgTypes[16]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GameEndPush.ProtoReflect.Descriptor instead.
func (*GameEndPush) Descriptor() ([]byte, []int) {
	return file_landlord_proto_rawDescGZIP(), []int{16}
}

func (x *GameEndPush) GetWinnerSeat() int32 {
	if x != nil {
		return x.WinnerSeat
	}
	return 0
}

func (x *GameEndPush) GetWinnerName() string {
	if x != nil {
		return x.WinnerName
	}
	return ""
}

func (x *GameEndPush) GetIsLandlord() bool {
	if x != nil {
		return x.IsLandlord
	}
	return false
}

func (x *GameEndPush) GetLandlordWin() bool {
	if x != nil {
		return x.LandlordWin
	}
	return false
}

func (x *GameEndPush) GetBidScore() int32 {
	if x != nil {
		return x.BidScore
	}
	return 0
}

func (x *GameEndPush) GetBombCount() int32 {
	if x != nil {
		return x.BombCount
	}
	return 0
}

func (x *GameEndPush) GetSpring() bool {
	if x != nil {
		return x.Spring
	}
	return false
}

// GameErrorPush 游戏错误推送
type GameErrorPush struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Code    int32  `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Message string `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
}

func (x *GameErrorPush) Reset() {
	*x = GameErrorPush{}
	if protoimpl.UnsafeEnabled {
		mi := &file_landlord_proto_msgTypes[17]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GameErrorPush) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GameErrorPush) ProtoMessage() {}

func (x *GameErrorPush) ProtoReflect() protoreflect.Message {
	mi := &file_landlord_proto_msgTypes[17]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GameErrorPush.ProtoReflect.Descriptor instead.
func (*GameErrorPush) Descriptor() ([]byte, []int) {
	return file_landlord_proto_rawDescGZIP(), []int{17}
}

func (x *GameErrorPush) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *GameErrorPush) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

// RoomInfoRequest 获取房间信息请求
type RoomInfoRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	RoomId string `protobuf:"bytes,1,opt,name=room_id,json=roomId,proto3" json:"room_id,omitempty"`
}

func (x *RoomInfoRequest) Reset() {
	*x = RoomInfoRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_landlord_proto_msgTypes[18]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RoomInfoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RoomInfoRequest) ProtoMessage() {}

func (x *RoomInfoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_landlord_proto_msgTypes[18]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RoomInfoRequest.ProtoReflect.Descriptor instead.
func (*RoomInfoRequest) Descriptor() ([]byte, []int) {
	return file_landlord_proto_rawDescGZIP(), []int{18}
}

func (x *RoomInfoRequest) GetRoomId() string {
	if x != nil {
		return x.RoomId
	}
	return ""
}

// RoomInfoResponse 获取房间信息响应
type RoomInfoResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	RoomId  string        `protobuf:"bytes,1,opt,name=room_id,json=roomId,proto3" json:"room_id,omitempty"`
	State   string        `protobuf:"bytes,2,opt,name=state,proto3" json:"state,omitempty"`
	Players []*PlayerInfo `protobuf:"bytes,3,rep,name=players,proto3" json:"players,omitempty"`
}

func (x *RoomInfoResponse) Reset() {
	*x = RoomInfoResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_landlord_proto_msgTypes[19]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RoomInfoResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RoomInfoResponse) ProtoMessage() {}

func (x *RoomInfoResponse) ProtoReflect() protoreflect.Message {
	mi := &file_landlord_proto_msgTypes[19]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RoomInfoResponse.ProtoReflect.Descriptor instead.
func (*RoomInfoResponse) Descriptor() ([]byte, []int) {
	return file_landlord_proto_rawDescGZIP(), []int{19}
}

func (x *RoomInfoResponse) GetRoomId() string {
	if x != nil {
		return x.RoomId
	}
	return ""
}

func (x *RoomInfoResponse) GetState() string {
	if x != nil {
		return x.State
	}
	return ""
}

func (x *RoomInfoResponse) GetPlayers() []*PlayerInfo {
	if x != nil {
		return x.Players
	}
	return nil
}

var File_landlord_proto protoreflect.FileDescriptor

var file_landlord_proto_rawDesc = []byte{
	0x0a, 0x0e, 0x6c, 0x61, 0x6e, 0x64, 0x6c, 0x6f, 0x72, 0x64, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x12, 0x0f, 0x6c, 0x61, 0x6e, 0x64, 0x6c, 0x6f, 0x72, 0x64, 0x5f, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x73, 0x22, 0x2e, 0x0a, 0x0b, 0x4a, 0x6f, 0x69, 0x6e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x12, 0x1f, 0x0a, 0x0b, 0x70, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x5f, 0x6e, 0x61, 0x6d, 0x65, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x70, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x4e, 0x61, 0x6d,
	0x65, 0x22, 0x22, 0x0a, 0x0a, 0x42, 0x69, 0x64, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12,
	0x14, 0x0a, 0x05, 0x73, 0x63, 0x6f, 0x72, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x05,
	0x73, 0x63, 0x6f, 0x72, 0x65, 0x22, 0x28, 0x0a, 0x0b, 0x50, 0x6c, 0x61, 0x79, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x12, 0x19, 0x0a, 0x08, 0x63, 0x61, 0x72, 0x64, 0x5f, 0x69, 0x64, 0x73,
	0x18, 0x01, 0x20, 0x03, 0x28, 0x05, 0x52, 0x07, 0x63, 0x61, 0x72, 0x64, 0x49, 0x64, 0x73, 0x22,
	0x0d, 0x0a, 0x0b, 0x50, 0x61, 0x73, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x22, 0x69,
	0x0a, 0x0c, 0x4a, 0x6f, 0x69, 0x6e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x12,
	0x0a, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x04, 0x63, 0x6f,
	0x64, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x12, 0x17, 0x0a, 0x07,
	0x72, 0x6f, 0x6f, 0x6d, 0x5f, 0x69, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x72,
	0x6f, 0x6f, 0x6d, 0x49, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x73, 0x65, 0x61, 0x74, 0x18, 0x04, 0x20,
	0x01, 0x28, 0x05, 0x52, 0x04, 0x73, 0x65, 0x61, 0x74, 0x22, 0x3b, 0x0a, 0x0b, 0x42, 0x69, 0x64,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x63, 0x6f, 0x64, 0x65,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x12, 0x18, 0x0a, 0x07,
	0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x6d,
	0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x22, 0x3c, 0x0a, 0x0c, 0x50, 0x6c, 0x61, 0x79, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x05, 0x52, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x6d, 0x65,
	0x73, 0x73, 0x61, 0x67, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x6d, 0x65, 0x73,
	0x73, 0x61, 0x67, 0x65, 0x22, 0x3c, 0x0a, 0x0c, 0x50, 0x61, 0x73, 0x73, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x05, 0x52, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x6d, 0x65, 0x73, 0x73,
	0x61, 0x67, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61,
	0x67, 0x65, 0x22, 0x7a, 0x0a, 0x0a, 0x50, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x49, 0x6e, 0x66, 0x6f,
	0x12, 0x10, 0x0a, 0x03, 0x75, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x75,
	0x69, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x73, 0x65, 0x61, 0x74, 0x18, 0x03,
	0x20, 0x01, 0x28, 0x05, 0x52, 0x04, 0x73, 0x65, 0x61, 0x74, 0x12, 0x13, 0x0a, 0x05, 0x69, 0x73,
	0x5f, 0x61, 0x69, 0x18, 0x04, 0x20, 0x01, 0x28, 0x08, 0x52, 0x04, 0x69, 0x73, 0x41, 0x69, 0x12,
	0x1d, 0x0a, 0x0a, 0x63, 0x61, 0x72, 0x64, 0x5f, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x18, 0x05, 0x20,
	0x01, 0x28, 0x05, 0x52, 0x09, 0x63, 0x61, 0x72, 0x64, 0x43, 0x6f, 0x75, 0x6e, 0x74, 0x22, 0xa1,
	0x01, 0x0a, 0x0d, 0x47, 0x61, 0x6d, 0x65, 0x53, 0x74, 0x61, 0x72, 0x74, 0x50, 0x75, 0x73, 0x68,
	0x12, 0x17, 0x0a, 0x07, 0x72, 0x6f, 0x6f, 0x6d, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x06, 0x72, 0x6f, 0x6f, 0x6d, 0x49, 0x64, 0x12, 0x35, 0x0a, 0x07, 0x70, 0x6c, 0x61,
	0x79, 0x65, 0x72, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x1b, 0x2e, 0x6c, 0x61, 0x6e,
	0x64, 0x6c, 0x6f, 0x72, 0x64, 0x5f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x73, 0x2e, 0x50, 0x6c, 0x61,
	0x79, 0x65, 0x72, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x07, 0x70, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x73,
	0x12, 0x1d, 0x0a, 0x0a, 0x79, 0x6f, 0x75, 0x72, 0x5f, 0x63, 0x61, 0x72, 0x64, 0x73, 0x18, 0x03,
	0x20, 0x03, 0x28, 0x05, 0x52, 0x09, 0x79, 0x6f, 0x75, 0x72, 0x43, 0x61, 0x72, 0x64, 0x73, 0x12,
	0x21, 0x0a, 0x0c, 0x66, 0x69, 0x72, 0x73, 0x74, 0x5f, 0x62, 0x69, 0x64, 0x64, 0x65, 0x72, 0x18,
	0x04, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0b, 0x66, 0x69, 0x72, 0x73, 0x74, 0x42, 0x69, 0x64, 0x64,
	0x65, 0x72, 0x22, 0x3a, 0x0a, 0x0b, 0x42, 0x69, 0x64, 0x54, 0x75, 0x72, 0x6e, 0x50, 0x75, 0x73,
	0x68, 0x12, 0x12, 0x0a, 0x04, 0x73, 0x65, 0x61, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52,
	0x04, 0x73, 0x65, 0x61, 0x74, 0x12, 0x17, 0x0a, 0x07, 0x6d, 0x61, 0x78, 0x5f, 0x62, 0x69, 0x64,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x06, 0x6d, 0x61, 0x78, 0x42, 0x69, 0x64, 0x22, 0x4d,
	0x0a, 0x0d, 0x42, 0x69, 0x64, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x50, 0x75, 0x73, 0x68, 0x12,
	0x12, 0x0a, 0x04, 0x73, 0x65, 0x61, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x04, 0x73,
	0x65, 0x61, 0x74, 0x12, 0x14, 0x0a, 0x05, 0x73, 0x63, 0x6f, 0x72, 0x65, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x05, 0x52, 0x05, 0x73, 0x63, 0x6f, 0x72, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d,
	0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x22, 0xbe, 0x01,
	0x0a, 0x13, 0x4c, 0x61, 0x6e, 0x64, 0x6c, 0x6f, 0x72, 0x64, 0x44, 0x65, 0x63, 0x69, 0x64, 0x65,
	0x64, 0x50, 0x75, 0x73, 0x68, 0x12, 0x23, 0x0a, 0x0d, 0x6c, 0x61, 0x6e, 0x64, 0x6c, 0x6f, 0x72,
	0x64, 0x5f, 0x73, 0x65, 0x61, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0c, 0x6c, 0x61,
	0x6e, 0x64, 0x6c, 0x6f, 0x72, 0x64, 0x53, 0x65, 0x61, 0x74, 0x12, 0x23, 0x0a, 0x0d, 0x6c, 0x61,
	0x6e, 0x64, 0x6c, 0x6f, 0x72, 0x64, 0x5f, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x0c, 0x6c, 0x61, 0x6e, 0x64, 0x6c, 0x6f, 0x72, 0x64, 0x4e, 0x61, 0x6d, 0x65, 0x12,
	0x21, 0x0a, 0x0c, 0x62, 0x6f, 0x74, 0x74, 0x6f, 0x6d, 0x5f, 0x63, 0x61, 0x72, 0x64, 0x73, 0x18,
	0x03, 0x20, 0x03, 0x28, 0x05, 0x52, 0x0b, 0x62, 0x6f, 0x74, 0x74, 0x6f, 0x6d, 0x43, 0x61, 0x72,
	0x64, 0x73, 0x12, 0x1d, 0x0a, 0x0a, 0x79, 0x6f, 0x75, 0x72, 0x5f, 0x63, 0x61, 0x72, 0x64, 0x73,
	0x18, 0x04, 0x20, 0x03, 0x28, 0x05, 0x52, 0x09, 0x79, 0x6f, 0x75, 0x72, 0x43, 0x61, 0x72, 0x64,
	0x73, 0x12, 0x1b, 0x0a, 0x09, 0x62, 0x69, 0x64, 0x5f, 0x73, 0x63, 0x6f, 0x72, 0x65, 0x18, 0x05,
	0x20, 0x01, 0x28, 0x05, 0x52, 0x08, 0x62, 0x69, 0x64, 0x53, 0x63, 0x6f, 0x72, 0x65, 0x22, 0x79,
	0x0a, 0x0c, 0x50, 0x6c, 0x61, 0x79, 0x54, 0x75, 0x72, 0x6e, 0x50, 0x75, 0x73, 0x68, 0x12, 0x12,
	0x0a, 0x04, 0x73, 0x65, 0x61, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x04, 0x73, 0x65,
	0x61, 0x74, 0x12, 0x19, 0x0a, 0x08, 0x63, 0x61, 0x6e, 0x5f, 0x70, 0x61, 0x73, 0x73, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x08, 0x52, 0x07, 0x63, 0x61, 0x6e, 0x50, 0x61, 0x73, 0x73, 0x12, 0x1d, 0x0a,
	0x0a, 0x6c, 0x61, 0x73, 0x74, 0x5f, 0x63, 0x61, 0x72, 0x64, 0x73, 0x18, 0x03, 0x20, 0x03, 0x28,
	0x05, 0x52, 0x09, 0x6c, 0x61, 0x73, 0x74, 0x43, 0x61, 0x72, 0x64, 0x73, 0x12, 0x1b, 0x0a, 0x09,
	0x6c, 0x61, 0x73, 0x74, 0x5f, 0x73, 0x65, 0x61, 0x74, 0x18, 0x04, 0x20, 0x01, 0x28, 0x05, 0x52,
	0x08, 0x6c, 0x61, 0x73, 0x74, 0x53, 0x65, 0x61, 0x74, 0x22, 0x8a, 0x01, 0x0a, 0x0e, 0x43, 0x61,
	0x72, 0x64, 0x50, 0x6c, 0x61, 0x79, 0x65, 0x64, 0x50, 0x75, 0x73, 0x68, 0x12, 0x12, 0x0a, 0x04,
	0x73, 0x65, 0x61, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x04, 0x73, 0x65, 0x61, 0x74,
	0x12, 0x14, 0x0a, 0x05, 0x63, 0x61, 0x72, 0x64, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x05, 0x52,
	0x05, 0x63, 0x61, 0x72, 0x64, 0x73, 0x12, 0x1b, 0x0a, 0x09, 0x68, 0x61, 0x6e, 0x64, 0x5f, 0x74,
	0x79, 0x70, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x68, 0x61, 0x6e, 0x64, 0x54,
	0x79, 0x70, 0x65, 0x12, 0x1d, 0x0a, 0x0a, 0x63, 0x61, 0x72, 0x64, 0x5f, 0x63, 0x6f, 0x75, 0x6e,
	0x74, 0x18, 0x04, 0x20, 0x01, 0x28, 0x05, 0x52, 0x09, 0x63, 0x61, 0x72, 0x64, 0x43, 0x6f, 0x75,
	0x6e, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x22, 0x32, 0x0a, 0x08, 0x50, 0x61, 0x73, 0x73, 0x50, 0x75,
	0x73, 0x68, 0x12, 0x12, 0x0a, 0x04, 0x73, 0x65, 0x61, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05,
	0x52, 0x04, 0x73, 0x65, 0x61, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x22, 0xe7, 0x01, 0x0a, 0x0b, 0x47,
	0x61, 0x6d, 0x65, 0x45, 0x6e, 0x64, 0x50, 0x75, 0x73, 0x68, 0x12, 0x1f, 0x0a, 0x0b, 0x77, 0x69,
	0x6e, 0x6e, 0x65, 0x72, 0x5f, 0x73, 0x65, 0x61, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52,
	0x0a, 0x77, 0x69, 0x6e, 0x6e, 0x65, 0x72, 0x53, 0x65, 0x61, 0x74, 0x12, 0x1f, 0x0a, 0x0b, 0x77,
	0x69, 0x6e, 0x6e, 0x65, 0x72, 0x5f, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x0a, 0x77, 0x69, 0x6e, 0x6e, 0x65, 0x72, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x1f, 0x0a, 0x0b,
	0x69, 0x73, 0x5f, 0x6c, 0x61, 0x6e, 0x64, 0x6c, 0x6f, 0x72, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28,
	0x08, 0x52, 0x0a, 0x69, 0x73, 0x4c, 0x61, 0x6e, 0x64, 0x6c, 0x6f, 0x72, 0x64, 0x12, 0x21, 0x0a,
	0x0c, 0x6c, 0x61, 0x6e, 0x64, 0x6c, 0x6f, 0x72, 0x64, 0x5f, 0x77, 0x69, 0x6e, 0x18, 0x04, 0x20,
	0x01, 0x28, 0x08, 0x52, 0x0b, 0x6c, 0x61, 0x6e, 0x64, 0x6c, 0x6f, 0x72, 0x64, 0x57, 0x69, 0x6e,
	0x12, 0x1b, 0x0a, 0x09, 0x62, 0x69, 0x64, 0x5f, 0x73, 0x63, 0x6f, 0x72, 0x65, 0x18, 0x05, 0x20,
	0x01, 0x28, 0x05, 0x52, 0x08, 0x62, 0x69, 0x64, 0x53, 0x63, 0x6f, 0x72, 0x65, 0x12, 0x1d, 0x0a,
	0x0a, 0x62, 0x6f, 0x6d, 0x62, 0x5f, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x18, 0x06, 0x20, 0x01, 0x28,
	0x05, 0x52, 0x09, 0x62, 0x6f, 0x6d, 0x62, 0x43, 0x6f, 0x75, 0x6e, 0x74, 0x12, 0x16, 0x0a, 0x06,
	0x73, 0x70, 0x72, 0x69, 0x6e, 0x67, 0x18, 0x07, 0x20, 0x01, 0x28, 0x08, 0x52, 0x06, 0x73, 0x70,
	0x72, 0x69, 0x6e, 0x67, 0x22, 0x3d, 0x0a, 0x0d, 0x47, 0x61, 0x6d, 0x65, 0x45, 0x72, 0x72, 0x6f,
	0x72, 0x50, 0x75, 0x73, 0x68, 0x12, 0x12, 0x0a, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x05, 0x52, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x6d, 0x65, 0x73,
	0x73, 0x61, 0x67, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x6d, 0x65, 0x73, 0x73,
	0x61, 0x67, 0x65, 0x22, 0x2a, 0x0a, 0x0f, 0x52, 0x6f, 0x6f, 0x6d, 0x49, 0x6e, 0x66, 0x6f, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x17, 0x0a, 0x07, 0x72, 0x6f, 0x6f, 0x6d, 0x5f, 0x69,
	0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x72, 0x6f, 0x6f, 0x6d, 0x49, 0x64, 0x22,
	0x78, 0x0a, 0x10, 0x52, 0x6f, 0x6f, 0x6d, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x12, 0x17, 0x0a, 0x07, 0x72, 0x6f, 0x6f, 0x6d, 0x5f, 0x69, 0x64, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x72, 0x6f, 0x6f, 0x6d, 0x49, 0x64, 0x12, 0x14, 0x0a, 0x05,
	0x73, 0x74, 0x61, 0x74, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x73, 0x74, 0x61,
	0x74, 0x65, 0x12, 0x35, 0x0a, 0x07, 0x70, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x73, 0x18, 0x03, 0x20,
	0x03, 0x28, 0x0b, 0x32, 0x1b, 0x2e, 0x6c, 0x61, 0x6e, 0x64, 0x6c, 0x6f, 0x72, 0x64, 0x5f, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x73, 0x2e, 0x50, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x49, 0x6e, 0x66, 0x6f,
	0x52, 0x07, 0x70, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x73, 0x42, 0x1f, 0x5a, 0x1d, 0x65, 0x78, 0x61,
	0x6d, 0x70, 0x6c, 0x65, 0x73, 0x2f, 0x64, 0x65, 0x6d, 0x6f, 0x2f, 0x6c, 0x61, 0x6e, 0x64, 0x6c,
	0x6f, 0x72, 0x64, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x73, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x33,
}

var (
	file_landlord_proto_rawDescOnce sync.Once
	file_landlord_proto_rawDescData = file_landlord_proto_rawDesc
)

func file_landlord_proto_rawDescGZIP() []byte {
	file_landlord_proto_rawDescOnce.Do(func() {
		file_landlord_proto_rawDescData = protoimpl.X.CompressGZIP(file_landlord_proto_rawDescData)
	})
	return file_landlord_proto_rawDescData
}

var file_landlord_proto_msgTypes = make([]protoimpl.MessageInfo, 20)
var file_landlord_proto_goTypes = []interface{}{
	(*JoinRequest)(nil),         // 0: landlord_protos.JoinRequest
	(*BidRequest)(nil),          // 1: landlord_protos.BidRequest
	(*PlayRequest)(nil),         // 2: landlord_protos.PlayRequest
	(*PassRequest)(nil),         // 3: landlord_protos.PassRequest
	(*JoinResponse)(nil),        // 4: landlord_protos.JoinResponse
	(*BidResponse)(nil),         // 5: landlord_protos.BidResponse
	(*PlayResponse)(nil),        // 6: landlord_protos.PlayResponse
	(*PassResponse)(nil),        // 7: landlord_protos.PassResponse
	(*PlayerInfo)(nil),          // 8: landlord_protos.PlayerInfo
	(*GameStartPush)(nil),       // 9: landlord_protos.GameStartPush
	(*BidTurnPush)(nil),         // 10: landlord_protos.BidTurnPush
	(*BidResultPush)(nil),       // 11: landlord_protos.BidResultPush
	(*LandlordDecidedPush)(nil), // 12: landlord_protos.LandlordDecidedPush
	(*PlayTurnPush)(nil),        // 13: landlord_protos.PlayTurnPush
	(*CardPlayedPush)(nil),      // 14: landlord_protos.CardPlayedPush
	(*PassPush)(nil),            // 15: landlord_protos.PassPush
	(*GameEndPush)(nil),         // 16: landlord_protos.GameEndPush
	(*GameErrorPush)(nil),       // 17: landlord_protos.GameErrorPush
	(*RoomInfoRequest)(nil),     // 18: landlord_protos.RoomInfoRequest
	(*RoomInfoResponse)(nil),    // 19: landlord_protos.RoomInfoResponse
}
var file_landlord_proto_depIdxs = []int32{
	8, // 0: landlord_protos.GameStartPush.players:type_name -> landlord_protos.PlayerInfo
	8, // 1: landlord_protos.RoomInfoResponse.players:type_name -> landlord_protos.PlayerInfo
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_landlord_proto_init() }
func file_landlord_proto_init() {
	if File_landlord_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_landlord_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*JoinRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_landlord_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BidRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_landlord_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PlayRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_landlord_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PassRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_landlord_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*JoinResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_landlord_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BidResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_landlord_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PlayResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_landlord_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PassResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_landlord_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PlayerInfo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_landlord_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GameStartPush); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_landlord_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BidTurnPush); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_landlord_proto_msgTypes[11].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BidResultPush); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_landlord_proto_msgTypes[12].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*LandlordDecidedPush); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_landlord_proto_msgTypes[13].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PlayTurnPush); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_landlord_proto_msgTypes[14].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CardPlayedPush); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_landlord_proto_msgTypes[15].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PassPush); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_landlord_proto_msgTypes[16].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GameEndPush); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_landlord_proto_msgTypes[17].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GameErrorPush); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_landlord_proto_msgTypes[18].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RoomInfoRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_landlord_proto_msgTypes[19].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RoomInfoResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_landlord_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   20,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_landlord_proto_goTypes,
		DependencyIndexes: file_landlord_proto_depIdxs,
		MessageInfos:      file_landlord_proto_msgTypes,
	}.Build()
	File_landlord_proto = out.File
	file_landlord_proto_rawDesc = nil
	file_landlord_proto_goTypes = nil
	file_landlord_proto_depIdxs = nil
}
